dism -online -enable-feature -FeatureName:NetFx4ServerFeatures
dism -online -enable-feature -FeatureName:NetFx4
dism -online -enable-feature -FeatureName:NetFx4Extended-ASPNET45
dism -online -enable-feature -FeatureName:IIS-WebServerRole
dism -online -enable-feature -FeatureName:IIS-WebServer
dism -online -enable-feature -FeatureName:IIS-CommonHttpFeatures
dism -online -enable-feature -FeatureName:IIS-Security
dism -online -enable-feature -FeatureName:IIS-RequestFiltering
dism -online -enable-feature -FeatureName:IIS-StaticContent
dism -online -enable-feature -FeatureName:IIS-DefaultDocument
dism -online -enable-feature -FeatureName:IIS-HttpErrors
dism -online -enable-feature -FeatureName:IIS-HttpRedirect
dism -online -enable-feature -FeatureName:IIS-WebDAV
dism -online -enable-feature -FeatureName:IIS-ApplicationDevelopment
dism -online -enable-feature -FeatureName:IIS-WebSockets
dism -online -enable-feature -FeatureName:IIS-ApplicationInit
dism -online -enable-feature -FeatureName:IIS-NetFxExtensibility
dism -online -enable-feature -FeatureName:IIS-NetFxExtensibility45
dism -online -enable-feature -FeatureName:IIS-ISAPIExtensions
dism -online -enable-feature -FeatureName:IIS-ISAPIFilter
dism -online -enable-feature -FeatureName:IIS-ServerSideIncludes
dism -online -enable-feature -FeatureName:IIS-HealthAndDiagnostics
dism -online -enable-feature -FeatureName:IIS-HttpLogging
dism -online -enable-feature -FeatureName:IIS-LoggingLibraries
dism -online -enable-feature -FeatureName:IIS-RequestMonitor
dism -online -enable-feature -FeatureName:IIS-HttpTracing
dism -online -enable-feature -FeatureName:IIS-CustomLogging
dism -online -enable-feature -FeatureName:IIS-ODBCLogging
dism -online -enable-feature -FeatureName:IIS-CertProvider
dism -online -enable-feature -FeatureName:IIS-BasicAuthentication
dism -online -enable-feature -FeatureName:IIS-WindowsAuthentication
dism -online -enable-feature -FeatureName:IIS-DigestAuthentication
dism -online -enable-feature -FeatureName:IIS-ClientCertificateMappingAuthentication
dism -online -enable-feature -FeatureName:IIS-IISCertificateMappingAuthentication
dism -online -enable-feature -FeatureName:IIS-URLAuthorization
dism -online -enable-feature -FeatureName:IIS-IPSecurity
dism -online -enable-feature -FeatureName:IIS-Performance
dism -online -enable-feature -FeatureName:IIS-HttpCompressionStatic
dism -online -enable-feature -FeatureName:IIS-HttpCompressionDynamic
dism -online -enable-feature -FeatureName:IIS-WebServerManagementTools
dism -online -enable-feature -FeatureName:IIS-ManagementConsole
dism -online -enable-feature -FeatureName:IIS-LegacySnapIn
dism -online -enable-feature -FeatureName:IIS-ManagementScriptingTools
dism -online -enable-feature -FeatureName:IIS-ManagementService
dism -online -enable-feature -FeatureName:IIS-IIS6ManagementCompatibility
dism -online -enable-feature -FeatureName:IIS-Metabase
dism -online -enable-feature -FeatureName:IIS-WMICompatibility
dism -online -enable-feature -FeatureName:IIS-LegacyScripts
dism -online -enable-feature -FeatureName:WAS-NetFxEnvironment
dism -online -enable-feature -FeatureName:IIS-HostableWebCore
dism -online -enable-feature -FeatureName:ADCertificateServicesRole
dism -online -enable-feature -FeatureName:CertificateServices
dism -online -enable-feature -FeatureName:CertificateEnrollmentPolicyServer
dism -online -enable-feature -FeatureName:CertificateEnrollmentServer
dism -online -enable-feature -FeatureName:Microsoft-Windows-Web-Services-for-Management-IIS-Extension
dism -online -enable-feature -FeatureName:NetFx3ServerFeatures
dism -online -enable-feature -FeatureName:NetFx3
dism -online -enable-feature -FeatureName:ADCertificateServicesManagementTools
dism -online -enable-feature -FeatureName:CertificateServicesManagementTools
